<project xmlns="http://maven.apache.org/POM/4.0.0">
  <artifactId>acme-parent</artifactId>
  <packaging>pom</packaging>
  <properties>
    <docker.image.prefix>acme</docker.image.prefix>
  </properties>
  <modules>
    <module>gateway</module>
    <module>service</module>
  </modules>
  <profiles>
    <profile>
      <id>buildDocker</id>
      <build>
        <plugins>
          <plugin>
            <artifactId>exec-maven-plugin</artifactId>
            <configuration>
              <arguments>
                <argument>build</argument>
                <argument>-t</argument>
                <argument>${docker.image.prefix}/${project.artifactId}</argument>
              </arguments>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
