"""Generated code (ctypes/clang2py bindings, protobuf) is excluded from static analysis.

Why: such files carry huge symbol counts but no architectural signal and explode the LSP
references phase — e.g. tinygrad's runtime/autogen bindings timed out `codeboarding full`.
"""

from repo_utils.ignore import RepoIgnoreManager
from static_analyzer.engine.language_adapter import _is_generated_source


def test_ignore_patterns_exclude_generated_bindings(tmp_path):
    (tmp_path / "pkg" / "runtime" / "autogen").mkdir(parents=True)
    (tmp_path / "pkg" / "runtime" / "autogen" / "nv.py").write_text("x = 1\n")
    (tmp_path / "proto").mkdir()
    (tmp_path / "proto" / "schema_pb2.py").write_text("x = 1\n")
    (tmp_path / "pkg" / "tensor.py").write_text("x = 1\n")

    im = RepoIgnoreManager(tmp_path)

    assert im.should_ignore(tmp_path / "pkg" / "runtime" / "autogen" / "nv.py")
    assert im.should_ignore(tmp_path / "proto" / "schema_pb2.py")
    assert not im.should_ignore(tmp_path / "pkg" / "tensor.py")


def test_is_generated_source_marker(tmp_path):
    marked = tmp_path / "marked.py"
    marked.write_text("# @generated by clang2py\nimport ctypes\n")
    assert _is_generated_source(marked)


def test_is_generated_source_large_ctypes_binding(tmp_path):
    big = tmp_path / "big.py"
    big.write_text("import ctypes\n" + "CONST = 1\n" * 30000)  # > 200 KB
    assert _is_generated_source(big)


def test_is_generated_source_keeps_handwritten(tmp_path):
    """A small, hand-written file that merely imports ctypes must NOT be flagged."""
    hand = tmp_path / "device.py"
    hand.write_text("import ctypes\n\n\ndef alloc(n):\n    return ctypes.create_string_buffer(n)\n")
    assert not _is_generated_source(hand)
